import type { NextPage } from 'next';
import Head from 'next/head';
import LoginForm from '../components/LoginForm/LoginForm';

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Авторизация</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <LoginForm />
      </main>
    </div>
  );
};

export default Login;
